import PDFDocument from 'pdfkit';

import { logger } from '../../config/logger';
import { prisma } from '../../lib/prisma';

import { escapeHtml, isEmailConfigured, sendEmail } from './email.service';

const reportOrange = '#B45309';
const reportInk = '#3D1F00';

type ReportPeriod = {
  start: Date;
  end: Date;
  label: string;
};

function formatMonth(date: Date) {
  return new Intl.DateTimeFormat('en-IN', {
    month: 'long',
    year: 'numeric',
    timeZone: 'UTC',
  }).format(date);
}

function formatDate(date: Date, timezone: string) {
  return new Intl.DateTimeFormat('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    timeZone: timezone,
  }).format(date);
}

function money(minor: number, currency: string) {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency,
    maximumFractionDigits: 2,
  }).format(minor / 100);
}

function safeLogoUrl(value: string | null) {
  if (!value) return null;
  try {
    const url = new URL(value);
    return url.protocol === 'https:' ? url.toString() : null;
  } catch {
    return null;
  }
}

function previousMonthPeriod(now = new Date()): ReportPeriod {
  const start = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - 1, 1));
  const end = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1));
  return { start, end, label: formatMonth(start) };
}

function buildReportPdf(input: {
  organizationName: string;
  branchName: string;
  timezone: string;
  currency: string;
  period: ReportPeriod;
  members: Array<{
    name: string;
    memberNumber: string;
    attendanceCount: number;
    workedMinutes: number;
    subscription: { name: string; status: string; start: Date; end: Date; amount: number } | null;
  }>;
}) {
  const document = new PDFDocument({ size: 'A4', margin: 42, bufferPages: true });
  const chunks: Buffer[] = [];
  document.on('data', (chunk: Buffer) => chunks.push(chunk));

  document.fillColor(reportOrange).fontSize(9).font('Helvetica-Bold').text('DAILIO', 42, 42);
  document.fillColor(reportInk).fontSize(22).text('Monthly member report', 42, 64);
  document.fillColor('#666666').fontSize(10).font('Helvetica');
  document.text(`${input.organizationName} · ${input.branchName}`, 42, 94);
  document.text(`${input.period.label} · timezone ${input.timezone}`, 42, 110);
  document.moveTo(42, 134).lineTo(553, 134).strokeColor('#E6D7C8').stroke();

  const totalAttendance = input.members.reduce((sum, member) => sum + member.attendanceCount, 0);
  const totalMinutes = input.members.reduce((sum, member) => sum + member.workedMinutes, 0);
  const activeSubscriptions = input.members.filter(
    (member) => member.subscription?.status === 'ACTIVE',
  ).length;

  document.fillColor(reportInk).font('Helvetica-Bold').fontSize(11).text('Overview', 42, 154);
  document.font('Helvetica').fontSize(10).fillColor('#333333');
  document.text(`Members: ${input.members.length}`, 42, 174);
  document.text(`Attendance sessions: ${totalAttendance}`, 170, 174);
  document.text(`Worked time: ${Math.floor(totalMinutes / 60)}h ${totalMinutes % 60}m`, 330, 174);
  document.text(`Active subscriptions: ${activeSubscriptions}`, 42, 192);

  let y = 228;
  const columns = [42, 154, 246, 322, 412, 486];
  document
    .fillColor('#F8F1EA')
    .rect(42, y - 5, 511, 25)
    .fill();
  document.fillColor(reportInk).font('Helvetica-Bold').fontSize(8);
  ['Member', 'Attendance', 'Worked', 'Plan', 'Ends', 'Status'].forEach((label, index) =>
    document.text(label, columns[index], y, { width: index === 0 ? 106 : 80 }),
  );
  y += 30;
  document.font('Helvetica').fontSize(8).fillColor('#333333');

  for (const member of input.members) {
    if (y > 760) {
      document.addPage();
      y = 48;
      document.fillColor(reportOrange).font('Helvetica-Bold').fontSize(9).text('DAILIO', 42, y);
      y += 24;
    }
    const subscription = member.subscription;
    const values = [
      member.name,
      String(member.attendanceCount),
      `${Math.floor(member.workedMinutes / 60)}h ${member.workedMinutes % 60}m`,
      subscription
        ? `${subscription.name} · ${money(subscription.amount, input.currency)}`
        : 'No plan',
      subscription ? formatDate(subscription.end, input.timezone) : '—',
      subscription?.status ?? '—',
    ];
    values.forEach((value, index) =>
      document.text(value, columns[index], y, {
        width: index === 0 ? 106 : 80,
        ellipsis: true,
      }),
    );
    document
      .moveTo(42, y + 15)
      .lineTo(553, y + 15)
      .strokeColor('#EEEEEE')
      .stroke();
    y += 27;
  }

  document
    .fillColor('#777777')
    .fontSize(8)
    .text(
      'Generated by Dailio · Attendance and subscription information is scoped to this branch.',
      42,
      790,
      { align: 'center', width: 511 },
    );
  document.end();
  return new Promise<Buffer>((resolve) => document.on('end', () => resolve(Buffer.concat(chunks))));
}

function reportEmailHtml(input: {
  organizationName: string;
  branchName: string;
  logoUrl: string | null;
  period: ReportPeriod;
  members: number;
}) {
  const logo = input.logoUrl
    ? `<img src="${escapeHtml(input.logoUrl)}" alt="${escapeHtml(input.organizationName)}" width="48" height="48" style="display:block;border-radius:12px;object-fit:cover" />`
    : `<div style="font-weight:800;font-size:22px;color:${reportOrange}">Dailio</div>`;
  return `<!doctype html><html><body style="margin:0;background:#faf8f6;font-family:Arial,sans-serif;color:#24170f"><div style="max-width:620px;margin:0 auto;padding:32px 20px"><div style="background:#fff;border:1px solid #eee4dc;border-radius:18px;padding:28px"><div style="margin-bottom:20px">${logo}</div><div style="font-size:22px;font-weight:700">Monthly member report</div><div style="color:#735f52;margin-top:6px">${escapeHtml(input.organizationName)} · ${escapeHtml(input.branchName)}</div><div style="color:#735f52;margin-top:2px">${escapeHtml(input.period.label)}</div><div style="margin-top:24px;padding:16px;background:#fff7ef;border-radius:12px;color:#5a3110">Attached is the branch report with attendance sessions, worked time, and subscription status for ${input.members} members.</div><p style="font-size:12px;color:#8b817b;margin:24px 0 0">This report is generated automatically by Dailio.</p></div></div></body></html>`;
}

export async function runMonthlyMemberReports(period = previousMonthPeriod()) {
  if (!isEmailConfigured()) return { branches: 0, sent: 0, skipped: 0 };

  const branches = await prisma.branch.findMany({
    where: { status: 'ACTIVE' },
    select: {
      id: true,
      name: true,
      timezone: true,
      organization_id: true,
      organization: { select: { name: true, logo_url: true, currency: true, status: true } },
      members: {
        where: { status: 'ACTIVE' },
        select: {
          member_number: true,
          user: { select: { name: true, email: true } },
          role: { select: { system_key: true } },
          attendance_sessions: {
            where: { clock_in_at: { gte: period.start, lt: period.end } },
            select: { worked_minutes: true },
          },
          subscriptions: {
            where: { status: { not: 'CANCELLED' } },
            orderBy: [{ end_date: 'desc' }],
            take: 1,
            select: {
              status: true,
              start_date: true,
              end_date: true,
              agreed_amount_minor: true,
              plan: { select: { name: true } },
            },
          },
        },
      },
    },
  });

  let sent = 0;
  let skipped = 0;
  for (const branch of branches) {
    if (branch.organization.status !== 'ACTIVE') continue;
    const owners = branch.members
      .filter((member) => member.role?.system_key === 'OWNER' && member.user.email)
      .map((member) => member.user.email as string);
    const recipients = [...new Set(owners)];
    if (recipients.length === 0) {
      skipped += 1;
      continue;
    }

    const members = branch.members.map((member) => {
      const subscription = member.subscriptions[0];
      return {
        name: member.user.name || member.member_number || 'Member',
        memberNumber: member.member_number ?? '—',
        attendanceCount: member.attendance_sessions.length,
        workedMinutes: member.attendance_sessions.reduce(
          (sum, session) => sum + (session.worked_minutes ?? 0),
          0,
        ),
        subscription: subscription
          ? {
              name: subscription.plan.name,
              status: subscription.status,
              start: subscription.start_date,
              end: subscription.end_date,
              amount: subscription.agreed_amount_minor,
            }
          : null,
      };
    });
    const pdf = await buildReportPdf({
      organizationName: branch.organization.name,
      branchName: branch.name,
      timezone: branch.timezone,
      currency: branch.organization.currency,
      period,
      members,
    });
    const subject = `${branch.organization.name} · ${branch.name} · ${period.label} member report`;
    for (const recipient of recipients) {
      try {
        const result = await sendEmail({
          to: recipient,
          subject,
          text: `Your Dailio monthly member report for ${period.label} is attached.`,
          html: reportEmailHtml({
            organizationName: branch.organization.name,
            branchName: branch.name,
            logoUrl: safeLogoUrl(branch.organization.logo_url),
            period,
            members: members.length,
          }),
          attachments: [
            {
              filename: `dailio-${branch.name.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}-${period.start.toISOString().slice(0, 7)}.pdf`,
              content: pdf,
              contentType: 'application/pdf',
            },
          ],
        });
        if (result) sent += 1;
        else skipped += 1;
      } catch (error) {
        skipped += 1;
        logger.warn('Monthly member report email failed', {
          branch_id: branch.id,
          error: (error as Error).message,
        });
      }
    }
  }
  return { branches: branches.length, sent, skipped };
}

export { previousMonthPeriod };
